### ISSUE TITLE
New implementation ignores rule for playing from discard

### ISSUE THREAD

**Issue by PhallenCassidy** [MarcinSc/gemp-lotr#74]
They Are Coming discarding a minion from hand, then playing it from discard at site 2: http://www.gempukku.com/gemp-lotr/game.html?replayId=Malachi$u6h10zfrvyjw889n

The Balrog, Flame of Udun exerting without playing anything from discard (no valid targets), site 5: http://www.gempukku.com/gemp-lotr/game.html?replayId=Phallen$x0vc020qv67v87mpN

Ulaire Nertea, Messenger of Dol Guldur playing minions from discard at The Great River (potentially related, playing from discard outside of actions specific to the shadow phase seem to ignore "cannot play" and unique rules):
http://www.gempukku.com/gemp-lotr/game.html?replayId=Ainoster$p17admjhy2kuux11

**Comment by MarcinSc** [comment]
Ok, these might be3 completely different issues. So, just to make sure I understand correctly, what is wrong with the replays you've linked, and please correct me if I'm understanding the problems:
1. They Are Coming - that player should not be able to play the minion that was discarded from hand by the cost.
2. Balrog - There was no legal targets after the cost of removing 2 was payed (there were before 2 was payed).
3. Nazgul - Checking playability rules - unique and "can't play from discard" rules.

**Comment by PhallenCassidy** [comment]
Yup! There are some cards from The Hobbit that might illustrate the third point more clearly, I can send you a replay to that if needed. I had hoped that all three stemmed from the same issue where Gemp isn't properly checking which cards are legal to play from discard before running through the action, but whatever the cause all of my efforts have come up flat.

**Comment by MarcinSc** [comment]
Ok, I've fixed all 3 mentioned cards. Please review the changes, especially for "They Are Coming" and "The Balrog" to see, what was missing.
The Ulaire Nertea was a bit more complicated, as the Duplicate and Optional effects where not passing the playability check through.
