### ISSUE TITLE
Actions from discard can block screen

### ISSUE THREAD

**Issue by PhallenCassidy** [MarcinSc/gemp-lotr#82]
If the game window is small enough that there is no area between the phase / twilight indicators and the alert box with the "pass" button, the "actionableCard" class for showing discard actions will create the card image with width and height 100% rather than a specific number of pixels. The clickable action area itself seems to be created with the "proper" size of 0 pixels, so the image will block much of the screen (including the "pass" box) and prevent actions from being taken. If the window is resized and an area is created, width and height for the image are given in pixels and those values persist after the window is shrunk again (until the next action is taken and the popup appears again). For mobile users that can't change the size of the window, there is not any way to progress.

**Comment by MarcinSc** [comment]
Hey, I've created "extra-actions-in-hand" branch, where all the "extra" actions like that (from discard, etc) should be displayed in hand with opacity 0.8.

Could you please test it? We could also lower the opacity if they are not distinguishable enough from rest of the hand.
