### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by tonywok** [MarcinSc/gemp-lotr#87]
Hi there, Neat codebase :) and thanks for making lotrtcg playable online -- especially when many are unable to meet.

I was wondering if this was the code being run on http://www.gempukku.com/ (feel free to close if not).

I noticed that the site does not use SSL. Would you be willing to add a certificate? You can get one for free using https://letsencrypt.org/

Happy to help as well :)

**Comment by tonywok** [comment]
@MarcinSc Is this the wrong repository?

**Comment by MarcinSc** [comment]
It is the repository, but since the images are stored on a different server - I'm not sure if that would work.

**Comment by tonywok** [comment]
@MarcinSc Ah, ok. I think I see what you mean. It appears at least some of the images are being hot-linked from `http://lotrtcgwiki.com`.

Looking at the network tab in the browser, it appears those image requests are being upgraded to HTTPS. You can reproduce this by loading something like [http://lotrtcgwiki.com/images/LOTR08009.jpg](http://lotrtcgwiki.com/images/LOTR08009.jpg) and observing it resolves to HTTPS.
