### ISSUE TITLE
warg

### ISSUE THREAD

**Issue by dc1701** [MarcinSc/gemp-lotr#90]
Warg seemed to let me exert any number of times in response to one action. This is confusing and nonsensical.

**Comment by PhallenCassidy** [comment]
This is correct, you can use a Response action as many time as you want to a particular trigger. If you have concerns about game mechanics, please leave them in the game hall or post them on the forums (https://lotrtcgwiki.com/forums/index.php?topic=7592.0) instead of making an issue ticket.
