### ISSUE TITLE
Unit Tests Incorrectly Apply Modifiers Twice

### ISSUE THREAD

**Issue by ketura** [MarcinSc/gemp-lotr#99]
When attempting to write unit tests for new cards, I'm finding that certain bonuses appear to be getting applied twice, and I have confirmed that this is a result of the game spawning modifiers twice within unit tests but not in an actual game:

![image](https://user-images.githubusercontent.com/1814132/111091226-4475d800-8500-11eb-9d68-4061be6ca13e.png)

Above we can see the twin modifiers affecting a Farin assigned to skirmish an Orc Scouting Band, which have the same filters and other traits which show they are both sourced from Farin's game text.  Once these modifiers are both applied, it puts Farin at an erroneous strength of 9, and Farin wins the resulting skirmish when he shouldn't.

Pitting Farin against an Orc Scouting Band within Gemp's client itself does not seem to have this duplicating effect.

This appears to affect modifiers in general.  At the very least I know it affects numeric modifers, including ModifyStrength and ModifySiteNumber.  

I don't know enough about the timing of when modifiers get added to the stack to be able to debug what exactly is causing the duplication.  I suspect the culprit is network-related, with a repetition getting swallowed in the real-world application but permitted in the instant-latency unit test context, but I admit that's nothing more than a hunch.

Here is a unit test that can be used to demonstrate this behavior:

```
    @Test
    public void FarinStrengthBoostWhileSkirmishingOrc() throws DecisionResultInvalidException, CardNotFoundException {
        //Pre-game setup
        initializeSimplestGame();

        // Farin, Dwarven Emissary; 5 strength, "while skirmishing an Orc, Farin is strength +2"
        final PhysicalCardImpl farin = createCard(P1, "1_11");
        _game.getGameState().addCardToZone(_game, farin, Zone.FREE_CHARACTERS);

        //Orc Scouting Band, 8 strength
        final PhysicalCardImpl orc = createCard(P2, "1_270");
        _game.getGameState().addCardToZone(_game, orc, Zone.SHADOW_CHARACTERS);

        skipMulligans();

        _game.getGameState().setTwilight(10);

        playerDecided(P1, "");

        // Pass in shadow
        playerDecided(P2, "");

        //Pass in maneuver
        playerDecided(P1, "");
        playerDecided(P2, "");

        //Pass in archery
        playerDecided(P1, "");
        playerDecided(P2, "");

        //Pass in assignment
        playerDecided(P1, "");
        playerDecided(P2, "");

        // assign Farin to an Orc
        playerDecided(P1, farin.getCardId() + " " + orc.getCardId());

        //Farin's strength is still the base of 5
        assertEquals(5, _game.getModifiersQuerying().getStrength(_game, farin));

        //Choose to resolve Farin's skirmish
        playerDecided(P1, "" + farin.getCardId());

        //This test fails.  Farin has two instances of the ModifyStrength modifier applied for some reason,
        // which puts him at 9 strength instead of the expected 7.
        assertEquals(5 + 2, _game.getModifiersQuerying().getStrength(_game, farin));

        playerDecided(P1, "");
        playerDecided(P2, "");

        // If the above test is commented out, then Farin wins the skirmish and applies skirmish wounds to the Orc
        assertEquals(0, _game.getGameState().getWounds(farin));
        assertEquals(1, _game.getGameState().getWounds(orc));

    }
```

**Comment by MarcinSc** [comment]
Fixed
